# Generated by Django 4.2.7 on 2023-11-21 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recycle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recycle',
            name='type',
            field=models.CharField(choices=[('Papel', 'Papel'), ('Plastico', 'Plastico'), ('Vidro', 'Vidro'), ('Metal', 'Metal'), ('Organico', 'Organico')], max_length=13),
        ),
    ]
